import { createContext, useContext, useState, ReactNode } from "react";

type Language = "tr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getCategoryMapping: (category: string) => string;
}

const translations = {
  tr: {
    // Header
    "header.login": "Giriş Yap",
    "header.signup": "Kayıt Ol",
    "header.logout": "Çıkış",
    
    // Navigation
    "nav.home": "Ana Sayfa",
    "nav.agents": "Ajanlar",
    "nav.myAgents": "Ajanlarım",
    "nav.pricing": "Fiyatlandırma",
    "nav.developer": "Geliştirici",
    
    // Home Page
    "home.hero.title": "Yapay Zeka Ajanlarının",
    "home.hero.subtitle": "Büyülü Dünyası",
    "home.hero.description": "Binlerce YZ ajanına erişin, kendi ajanlarınızı satışa sunun ve dijital dönüşümünüzü hızlandırın.",
    "home.hero.cta": "Ajanları Keşfet",
    "home.hero.learn": "Geliştirici Ol",
    "home.hero.slogan": "Herkesin akıllı bir asistana ihtiyacı vardır.",
    "home.categories.title": "Kategoriler",
    "home.featured.title": "Öne Çıkan Ajanlar",
    "home.view.all": "Tümünü Görüntüle",
    "home.howItWorks.title": "Nasıl Çalışır?",
    "home.howItWorks.subtitle": "Sadece üç adımda AI ajanlarından yararlanmaya başlayın.",
    "home.howItWorks.step1.title": "Keşfet & Seç",
    "home.howItWorks.step1.description": "İhtiyacınıza uygun YZ ajanını kategoriler arasından kolayca bulun ve özelliklerini inceleyin.",
    "home.howItWorks.step2.title": "Plan Seç",
    "home.howItWorks.step2.description": "İlginizi çeken ajan için size en uygun planı seçin ve gerekli izinleri onaylayın.",
    "home.howItWorks.step3.title": "Hemen Kullan",
    "home.howItWorks.step3.description": "Kullanım sayfasına gidin ve ajanınız iş süreçlerinizi otomatik olarak optimize etsin.",
    "home.howItWorks.cta.title": "Hemen Başlamaya Hazır mısınız?",
    "home.howItWorks.cta.description": "Binlerce AI ajanı arasından size en uygun olanı bulun ve dijital dönüşümünüzü hızlandırın.",
    "home.howItWorks.cta.button": "Ücretsiz Başlayın",
    "home.game.title": "Mıknatıs Oyunu",
    "home.game.description": "Fareyi hareket ettirin ve mıknatısın çekici gücünü hissedin! Mıknatısı sürükleyerek parçacıkları toplayın.",
    "home.game.instruction": "💡 Fareyi hareket ettirin ve mıknatıs etkisini görün",
    "home.game.congratulations": "Tebrikler!",
    "home.game.collectedAll": "Tüm parçacıkları topladınız!",
    "home.game.playAgain": "Tekrar Oyna",
    "home.game.interactiveExperience": "İnteraktif Deneyim",
    "home.game.collected": "Toplandı:",
    "home.stats.agents": "Demo Ajan",
    "home.stats.users": "Demo Kullanıcısı",
    "home.stats.support": "Destek",
    "home.stats.agents.count": "1",
    "home.stats.users.count": "10+",
    "home.stats.support.count": "24/7",
    
    // Magnetic Agents Section
    "home.magneticAgents.title": "Dikkat, Manyetik Alan!",
    "home.magneticAgents.description": "Gelecekte sunacağımız özel ajanlarımızı keşfedin; bu manyetik çekime karşı koymak imkansız gibi görünüyor!",
    "home.magneticAgents.moreToCome": "Daha fazlası geliyor...",
    "home.magneticAgents.gmail.title": "Gmail Ajan",
    "home.magneticAgents.gmail.description": "E-postalarınızı otomatik olarak yönetin, yanıtlayın ve organize edin.",
    "home.magneticAgents.tryOn.title": "Try On Ajan",
    "home.magneticAgents.tryOn.description": "Kıyafetleri sanal olarak deneyin ve stil önerileri alın.",
    "home.magneticAgents.instagram.title": "Instagram DM Kontrol",
    "home.magneticAgents.instagram.description": "Instagram mesajlarınızı otomatik olarak yönetin ve yanıtlayın.",
    "home.magneticAgents.whatsapp.title": "WhatsApp Ajan",
    "home.magneticAgents.whatsapp.description": "WhatsApp mesajlarınızı akıllıca yönetin ve otomatik yanıtlar oluşturun.",
    
                // Future Vision
            "home.magneticAgents.futureTitle": "Geleceğin Ajanları Burada Başlıyor",
            "home.magneticAgents.futureDescription": "Daha fazla ajan ve sektör geliyor! Her ihtiyaca özel çözümler.",
    
            "home.magneticAgents.customerVision": "Her müşteri farklı bir dünyadır. Bunu biliyoruz ve ürünlerimizi bu vizyonla geliştiriyoruz.",
    
    // Industries
    "home.magneticAgents.industries.beauty.title": "Güzellik Merkezleri",
    "home.magneticAgents.industries.beauty.description": "Randevu yönetimi, müşteri takibi ve pazarlama otomasyonu ile işinizi büyütün.",
    "home.magneticAgents.industries.boutique.title": "Butikler & Küçük İşletmeler",
    "home.magneticAgents.industries.boutique.description": "Stok yönetimi, müşteri ilişkileri ve sosyal medya otomasyonu ile verimliliğinizi artırın.",
    "home.magneticAgents.industries.it.title": "Kurumsal Profesyoneller",
    "home.magneticAgents.industries.it.description": "Ofis çalışanları, yöneticiler ve beyaz yakalı profesyoneller için akıllı asistanlar.",
    "home.magneticAgents.industries.students.title": "Öğrenciler",
    "home.magneticAgents.industries.students.description": "Ödev yardımı, araştırma ve öğrenme süreçlerinizi hızlandırın.",
    "home.magneticAgents.industries.aiEnthusiasts.title": "AI Meraklıları",
    "home.magneticAgents.industries.aiEnthusiasts.description": "Yapay zeka ajanlarının sınırlarını keşfedin ve yeni kullanım alanları yaratın.",
    "home.magneticAgents.industries.automation.title": "Otomasyon",
    "home.magneticAgents.industries.automation.description": "İş süreçlerinizi otomatikleştirin ve verimliliğinizi maksimuma çıkarın.",
    
    // Agent Store
    "store.title": "YZ Ajan",
    "store.title.highlight": "Mağazası",
    "store.description": "Binlerce yapay zeka ajanı arasından ihtiyacınıza en uygun olanları keşfedin. Her kategoriden profesyonel çözümler burada.",
    "store.search.placeholder": "Ajan ara...",
    "store.sort.popular": "Popüler",
    "store.sort.price": "Fiyat",
    "store.sort.name": "İsim",
    "store.view.grid": "Izgara",
    "store.view.list": "Liste",
    
    // Categories
    "category.all": "Tümü",
    "category.writing": "Yazım",
    "category.visual": "Görsel",
    "category.audio": "Ses",
    "category.analysis": "Analiz",
    "category.chat": "Sohbet",
    "category.code": "Kod",
    "category.language": "Dil",
    "category.marketing": "Pazarlama",
    
    // Agent Status
    "status.active": "Aktif",
    "status.popular": "Popüler",
    "status.new": "Yeni",
    "status.trend": "Trend",
    "status.pro": "Pro",
    "status.automatic": "Otomatik",
    
    // Pricing
    "pricing.monthly": "/ay",
    "pricing.yearly": "/yıl",
    "pricing.free": "Ücretsiz",
    "pricing.free.description": "Temel özelliklerle başlayın",
    "pricing.free.feature1": "Sınırlı ajan özellikleri",
    "pricing.free.feature2": "Düşük kotalı kullanım",
    "pricing.free.feature3": "Temel entegrasyonlar",
    "pricing.free.limitation1": "Özel entegrasyonlar yok",
    "pricing.free.limitation2": "Öncelikli destek yok",
    "pricing.free.button": "Ücretsiz Başla",
    "pricing.free.note": "İstediğiniz zaman iptal edebilirsiniz",
    "pricing.plus": "Plus",
    "pricing.plus.description": "Gelişmiş özellikler ve yüksek kotalar",
    "pricing.plus.feature1": "Gelişmiş ajan özellikleri",
    "pricing.plus.feature2": "Yüksek kotalı kullanım",
    "pricing.plus.feature3": "Yüksek API erişimi",
    "pricing.plus.feature4": "Öncelikli destek",
    "pricing.plus.feature5": "Özel entegrasyonlar",
    "pricing.plus.limitation1": "Sınırsız kullanım yok",
    "pricing.plus.button": "14 Gün Ücretsiz Dene",
    "pricing.premium": "Premium",
    "pricing.premium.description": "Tüm gelişmiş özellikler ve sınırsız kotalar",
    "pricing.premium.feature1": "Daha gelişmiş ajan özellikleri",
    "pricing.premium.feature2": "Sınırsız kullanım",
    "pricing.premium.feature3": "Tam API erişimi",
    "pricing.premium.feature4": "7/24 öncelikli destek",
    "pricing.premium.feature5": "Özel entegrasyonlar",
    "pricing.premium.feature6": "Gelişmiş analitik",
    "pricing.premium.feature7": "Takım işbirliği",
    "pricing.premium.button": "Satış Ekibi ile Görüş",
    "pricing.premium.note": "Özel fiyatlandırma için iletişime geçin",
    "pricing.mostPopular": "En Popüler",
    "pricing.cancelNote": "İstediğiniz zaman iptal edebilirsiniz",
    "pricing.title": "Size Uygun Planı",
    "pricing.titleHighlight": "Seçin",
    "pricing.subtitle": "Her AI ajanı için uygun plan seçenekleri. Yıllık ödemede %20 indirim fırsatı.",
    "pricing.paymentOptions.title": "Ödeme Seçenekleri",
    "pricing.paymentOptions.description": "Her plan yıllık veya aylık olarak alınabilir. Yıllık ödemelerde ay bazında %20 indirim uygulanır.",
    "pricing.faq.title": "Sıkça Sorulan Sorular",
    "pricing.faq.subtitle": "Fiyatlandırma planlarımız hakkında en çok merak edilen sorular.",
    "pricing.faq.q1.title": "Fiyatlar ajan başına mı hesaplanıyor?",
    "pricing.faq.q1.answer": "Evet, Agent Magnet'te her bir ajan ayrı olarak satılır. Her ajanın fiyatı farklı olabilir. Ödeme sayfasında detaylı olarak inceleyebilirsiniz.",
    "pricing.faq.q2.title": "Yıllık ödeme indirimi nasıl çalışır?",
    "pricing.faq.q2.answer": "Yıllık ödemede aylık ücretin %20 indirimlisini peşin olarak ödersiniz. Bu size yıllık %20 tasarruf sağlar.",
    "pricing.faq.q3.title": "Farklı ajanlar için farklı planlar seçebilir miyim?",
    "pricing.faq.q3.answer": "Evet, her AI ajanı için farklı plan seçebilirsiniz. Örneğin bir ajan için Premium, diğeri için Plus planı kullanabilirsiniz.",
    "pricing.faq.q4.title": "Kurumsal çözümler için ne yapmalıyım?",
    "pricing.faq.q4.answer": "Çoklu ajan yönetimi, özel entegrasyonlar ve kurumsal çözümler için satış ekibimizle iletişime geçebilirsiniz.",
    "pricing.contact.title": "Özel İhtiyaçlarınız mı Var?",
    "pricing.contact.description": "Kurumsal çözümler, çoklu ajan yönetimi, özel entegrasyonlar ve hacim indirimleri için satış ekibimizle iletişime geçin.",
    "pricing.contact.button": "Ekibimizle İletişime Geç",
    
    // Developer Page
    "developer.title": "Geliştirici",
    "developer.titleHighlight": "Portalı",
    "developer.subtitle": "Kendi AI ajanınızı platform mağazasına yükleyin ve dünya çapında kullanıcılara ulaşın.",
    "developer.comingSoon.title": "Yakında Geliyor!",
    "developer.comingSoon.description": "Geliştirici portalımız şu anda geliştirme aşamasındadır. Yakın gelecekte kullanıma sunulacaktır. Geliştirici olmakla ilgileniyorsanız lütfen aşağıdaki forma mail adresinizi bırakın. Haydi birlikte harika şeyler üretelim!",
    "developer.comingSoon.button": "Geliştirici Formu",
    "developer.benefits.title": "Geliştirici Avantajları",
    "developer.benefits.subtitle": "Platformumuzda ajan yayınlayarak elde edeceğiniz faydalar",
    "developer.benefits.global.title": "Global Erişim",
    "developer.benefits.global.description": "Dünya çapında milyonlarca kullanıcıya ulaşın ve ajanınızı tanıtın.",
    "developer.benefits.revenue.title": "Gelir Elde Edin",
    "developer.benefits.revenue.description": "Ajanınızın satışından %70'e kadar komisyon kazanın.",
    "developer.benefits.community.title": "Geliştirici Topluluğu",
    "developer.benefits.community.description": "Diğer geliştiricilerle bağlantı kurun ve deneyimlerinizi paylaşın.",
    "developer.benefits.support.title": "Teknik Destek",
    "developer.benefits.support.description": "7/24 teknik destek ve geliştirme araçları ile desteklenin.",
    "developer.features.title": "Platform Özellikleri",
    "developer.features.subtitle": "Geliştiriciler için özel olarak tasarlanmış araçlar ve özellikler",
    "developer.features.sdk.title": "Gelişmiş SDK",
    "developer.features.sdk.description": "Kapsamlı API ve SDK ile ajanınızı kolayca entegre edin.",
    "developer.features.easyUpload.title": "Kolay Yükleme",
    "developer.features.easyUpload.description": "Tek tıkla ajanınızı yükleyin ve mağazada yayınlayın.",
    "developer.features.analytics.title": "Detaylı Analitik",
    "developer.features.analytics.description": "Ajanınızın performansını ve kullanım istatistiklerini takip edin.",
    "developer.features.marketing.title": "Pazarlama Desteği",
    "developer.features.marketing.description": "Ajanınızı tanıtmak için pazarlama araçları ve kampanyalar.",
    "developer.stats.title": "Platform İstatistikleri",
    "developer.stats.subtitle": "Geliştirici topluluğumuzun büyümesi",
    "developer.stats.developers.count": "500+",
    "developer.stats.developers.label": "Geliştirici",
    "developer.stats.agents.count": "1000+",
    "developer.stats.agents.label": "Yayınlanan Ajan",
    "developer.stats.revenue.count": "₺2M+",
    "developer.stats.revenue.label": "Toplam Gelir",
    "developer.stats.countries.count": "50+",
    "developer.stats.countries.label": "Ülke",
    
    // My Agents Page
    "myAgents.title": "Ajanlarım",
    "myAgents.description": "Satın aldığınız ajanları yönetin ve kullanın",
    "myAgents.gmailAgent": "Gmail Ajan",
    "myAgents.useGmail": "Gmail Kullan",
    "myAgents.useAgent": "Ajanı Kullan",
    "myAgents.gmailDescription": "Gmail entegrasyonu ile e-postalarınızı yönetin",
    "myAgents.usageCount": "Kullanım Sayısı:",
    "myAgents.lastUsed": "Son Kullanım:",
    "myAgents.purchaseDate": "Satın alınma:",
    "myAgents.unknown": "Bilinmiyor",
    "myAgents.buyMoreAgents": "Daha Fazla Agent Satın Al",
    "myAgents.noAgentsTitle": "Henüz Agent Satın Almadınız",
    "myAgents.noAgentsDescription": "Agent mağazasından agent satın alarak başlayın.",
    "myAgents.goToStore": "Agent Mağazasına Git",
    "myAgents.loading": "Agentlarınız yükleniyor...",
    "myAgents.errorTitle": "Hata Oluştu",
    "myAgents.errorDescription": "Agentlarınız yüklenirken bir hata oluştu.",
    "myAgents.tryAgain": "Tekrar Dene",
    
    // Agent Detail Page
    "agentDetail.purchase": "Ajan'ı Al",
    "agentDetail.purchasing": "Satın Alınıyor...",
    "agentDetail.loginAndPurchase": "Giriş Yap ve Ajan'ı Al",
    "agentDetail.alreadyOwned": "Bu ajana sahipsiniz",
    "agentDetail.alreadyOwnedDescription": "Ajanlarım bölümünden kullanmaya devam edin.",
    "agentDetail.goToMyAgents": "Ajanlarım'a Git",
    "agentDetail.planSelection": "Plan Seçimi",
    "agentDetail.billing": "Faturalama:",
    "agentDetail.monthly": "Aylık",
    "agentDetail.yearly": "Yıllık %20 indirim",
    "agentDetail.planFeatures": "Planı Özellikleri",
    "agentDetail.planIntegrations": "Planında Kullanılabilir Entegrasyonlar",
    "agentDetail.monthlySubscription": "Aylık abonelik",
    "agentDetail.yearlySubscription": "Yıllık abonelik",
    "agentDetail.perYear": "/yıl",
    "agentDetail.cancelAnytime": "İstediğiniz zaman iptal edebilirsiniz. Kredi kartı gerekmez.",
    "agentDetail.fastSetup": "Hızlı Kurulum",
    "agentDetail.secure": "Güvenli",
    "agentDetail.globalAccess": "Global Erişim",
    "agentDetail.demoNote": "Bu plan henüz demo sürümümüzde yer almamaktadır. Üzerine çalışılmaktadır.",
    "agentDetail.backToAgents": "Ajanlar Mağazasına Dön",
    "agentDetail.free": "Ücretsiz",
    "agentDetail.perMonth": "/ay",
    "agentDetail.freeDescription": "Süresiz ücretsiz",
    "agentDetail.yearlyPayment": "yıllık ödeme",
    "agentDetail.yearlySavings": "Yıllık ödemeyle %20 tasarruf edin!",
    "agentDetail.freeCreditCard": "Kredi kartı gerektirmez. İstediğiniz zaman yükseltebilirsiniz.",
    "agentDetail.moreInPremium": "daha fazla Premium'da",
    "agentDetail.planSelectionTitle": "Plan Seçimi",
    "agentDetail.monthlyToggle": "Aylık",
    "agentDetail.yearlyToggle": "Yıllık %20 İndirim",
    "agentDetail.freePlan": "Ücretsiz",
    "agentDetail.plusPlan": "Plus",
    "agentDetail.premiumPlan": "Premium",
    "agentDetail.popular": "Popüler",
    "agentDetail.dailyQueries": "Günlük 5 sorgu",
    "agentDetail.last10Emails": "Son 10 mailinizin özetleri",
    "agentDetail.emailExtension": "example@gmail.com uzantılı mail adresleri ile çalışır",
    "agentDetail.demoPlanNote": "Bu plan henüz demo sürümümüzde yer almamaktadır. Üzerine çalışılmaktadır.",
    
    // Agent Start Page
    "agentStart.title": "Giriş Yapın",
    "agentStart.description": "ajan'ını kullanabilmek için önce giriş yapmanız gerekiyor.",
    "agentStart.whyLogin": "Neden giriş yapmalıyım?",
    "agentStart.loginReason1": "Ajan kullanımınızı takip edebiliriz",
    "agentStart.loginReason2": "Güvenli ve kişiselleştirilmiş deneyim",
    "agentStart.loginReason3": "Kullanım geçmişinizi görebilirsiniz",
    "agentStart.googleLogin": "Google ile Giriş Yap",
    
    // Gmail Agent Usage
    "gmail.title": "Gmail Ajanı",
    "gmail.description": "Gmail hesabınızdan son maillerinizi görüntüleyin ve AI ile özetleyin",
    "gmail.backToAgent": "Ajan'a Dön",
    "gmail.connectGmail": "Gmail Hesabımı Bağla",
    "gmail.getEmails": "Mailleri Getir",
    "gmail.loading": "Yükleniyor...",
    "gmail.loadingEmails": "Mailler yükleniyor...",
    "gmail.showSnippets": "Snippet'leri Göster",
    "gmail.hideSnippets": "Snippet'leri Gizle",
    "gmail.recentEmails": "Son Mailler",
    "gmail.aiSummary": "Kısa Özet",
    "gmail.noEmails": "Mail Bulunamadı",
    "gmail.noEmailsDescription": "Gmail hesabınızda mail bulunamadı veya henüz mailleri getirmediniz.",
    "gmail.connectRequired": "Gmail Bağlantısı Gerekli",
    "gmail.connectDescription": "Gmail hesabınızı bağlayarak maillerinizi görüntüleyebilir ve AI ile özetleyebilirsiniz.",
    "gmail.aiFeature": "AI Özetleme Özelliği",
    "gmail.aiFeature1": "Her e-posta için AI özeti oluşturulur",
    "gmail.aiFeature2": "Rate limit nedeniyle kademeli işlenir (2 saniye aralıklarla)",
    "gmail.aiFeature3": "Türkçe, kısa ve öz özetler",
    "gmail.aiFeature4": "Google Gemini 2.0 Flash modeli kullanılır",
    "gmail.accountConnected": "Gmail hesabınız bağlı - Maillerinizi getirebilirsiniz",
    "gmail.disconnect": "Bağlantıyı Kes",
    "gmail.connectionExpired": "Gmail Bağlantısı Süresi Dolmuş",
    "gmail.connectionExpiredDesc": "Gmail hesabınızla olan bağlantı süresi dolmuş. Maillerinizi görüntülemek için tekrar bağlanmanız gerekiyor.",
    "gmail.connectionExpiredReason": "Bu durum genellikle güvenlik nedeniyle veya uzun süre kullanılmadığında oluşur.",
    "gmail.connectionActive": "Gmail Bağlantısı Aktif",
    "gmail.connectionActiveDesc": "Maillerinizi görüntüleyebilir ve özetleyebilirsiniz.",
    "gmail.reconnect": "Tekrar Bağlan",
    "gmail.getLast10Emails": "Son 10 Maili Getir",
    "gmail.dailyUsageText": "Günlük kullanım hakkınızın {used}/{total}'ini kullandınız",
    "gmail.reset": "Reset",
    "gmail.remaining": "kaldı",
    "gmail.lastRightsRemaining": "Son {count} hakkınız kaldı",
    "gmail.dailyLimitReached": "Günlük limit doldu. Yarın tekrar deneyin.",
    
    // Common
    "common.loading": "Yükleniyor...",
    "common.error": "Hata Oluştu",
    "common.try_again": "Tekrar Dene",
    "common.tomorrow": "Yarın",
    "common.today": "Bugün",
    "common.days": "g",
    "test.loadingAgents": "Ajanlar yükleniyor...",
    "test.loadingAuth": "Kimlik doğrulama yükleniyor...",
    "test.testIntegration": "Test the integration",
    "test.testIntegrationDesc": "by clicking \"Test API Connection\"",
    "common.back_home": "Ana Sayfaya Dön",
    
    // Footer
    "footer.platform": "Platform",
    "footer.support": "Destek",
    "footer.help": "Yardım Merkezi",
    "footer.docs": "Dokümantasyon",
    "footer.contact": "İletişim",
    "footer.community": "Topluluk",
    "footer.privacy": "Gizlilik Politikası",
    "footer.terms": "Kullanım Şartları",
    "footer.cookies": "Çerezler",
    "footer.rights": "© 2025 Agent Magnet. Tüm hakları saklıdır.",
    
    // 404 Page
    "notFound.title": "404 Sayfa Bulunamadı",
    "notFound.description": "Sayfayı router'a eklemeyi unuttunuz mu?"
  },
  en: {
    // Header
    "header.login": "Sign In",
    "header.signup": "Sign Up",
    "header.logout": "Logout",
    
    // Navigation
    "nav.home": "Home",
    "nav.agents": "Agents",
    "nav.myAgents": "My Agents",
    "nav.pricing": "Pricing",
    "nav.developer": "Developer",
    
    // Home Page
    "home.hero.title": "The Magical World of",
    "home.hero.subtitle": "AI Agents",
    "home.hero.description": "Access thousands of AI agents, sell your own agents, and accelerate your digital transformation.",
    "home.hero.cta": "Explore Agents",
    "home.hero.learn": "Become Developer",
    "home.hero.slogan": "Everyone needs a smart assistant.",
    "home.categories.title": "Categories",
    "home.featured.title": "Featured Agents",
    "home.view.all": "View All",
    "home.howItWorks.title": "How It Works?",
    "home.howItWorks.subtitle": "Start leveraging AI agents in just three steps.",
    "home.howItWorks.step1.title": "Discover & Select",
    "home.howItWorks.step1.description": "Easily find and explore AI agents that suit your needs from thousands of options.",
    "home.howItWorks.step2.title": "Choose Plan",
    "home.howItWorks.step2.description": "Choose the most suitable plan for the agent you are interested in and approve the required permissions.",
    "home.howItWorks.step3.title": "Use Now",
    "home.howItWorks.step3.description": "Go to the usage page and let your agent optimize your work processes automatically.",
    "home.howItWorks.cta.title": "Ready to get started?",
    "home.howItWorks.cta.description": "Find the most suitable one from thousands of AI agents and accelerate your digital transformation.",
    "home.howItWorks.cta.button": "Start Free",
    "home.game.title": "Magnetic Game",
    "home.game.description": "Move the mouse and feel the magnetic attraction! Drag the magnet to collect particles.",
    "home.game.instruction": "💡 Move the mouse and see the magnetic effect!",
    "home.game.congratulations": "Congratulations!",
    "home.game.collectedAll": "You collected all the particles!",
    "home.game.playAgain": "Play Again",
    "home.game.interactiveExperience": "Interactive Experience",
    "home.game.collected": "Collected:",
    "home.stats.agents": "Demo Agent",
    "home.stats.users": "Demo Users",
    "home.stats.support": "Support",
    "home.stats.agents.count": "1",
    "home.stats.users.count": "10+",
    "home.stats.support.count": "24/7",
    
    // Magnetic Agents Section
    "home.magneticAgents.title": "Warning, Magnetic Field!",
    "home.magneticAgents.description": "Discover the special agents we will be releasing in the future; resisting this magnetic pull seems impossible!",
    "home.magneticAgents.moreToCome": "More to come...",
    "home.magneticAgents.gmail.title": "Gmail Agent",
    "home.magneticAgents.gmail.description": "Manage your emails automatically, respond, and organize them.",
    "home.magneticAgents.tryOn.title": "Try On Agent",
    "home.magneticAgents.tryOn.description": "Try on clothes virtually and get style suggestions.",
    "home.magneticAgents.instagram.title": "Instagram DM Control",
    "home.magneticAgents.instagram.description": "Automatically manage and respond to your Instagram messages.",
    "home.magneticAgents.whatsapp.title": "WhatsApp Agent",
    "home.magneticAgents.whatsapp.description": "Intelligently manage your WhatsApp messages and create automatic responses.",
    
                // Future Vision
            "home.magneticAgents.futureTitle": "The Future of Agents Starts Here",
            "home.magneticAgents.futureDescription": "More agents and industries coming! Custom solutions for every need.",
    
            "home.magneticAgents.customerVision": "Every customer is a different world. We know it and we develop our products with this vision.",
    
    // Industries
    "home.magneticAgents.industries.beauty.title": "Beauty & Wellness",
    "home.magneticAgents.industries.beauty.description": "Grow your business with appointment management, customer tracking, and marketing automation.",
    "home.magneticAgents.industries.boutique.title": "Boutiques & Small Business",
    "home.magneticAgents.industries.boutique.description": "Increase your efficiency with inventory management, customer relations, and social media automation.",
    "home.magneticAgents.industries.it.title": "Corporate Professionals",
    "home.magneticAgents.industries.it.description": "Smart assistants for office workers, managers, and white-collar professionals.",
    "home.magneticAgents.industries.students.title": "Students",
    "home.magneticAgents.industries.students.description": "Accelerate your homework, research, and learning processes.",
    "home.magneticAgents.industries.aiEnthusiasts.title": "AI Enthusiasts",
    "home.magneticAgents.industries.aiEnthusiasts.description": "Explore the boundaries of AI agents and create new use cases.",
    "home.magneticAgents.industries.automation.title": "Automation",
    "home.magneticAgents.industries.automation.description": "Automate your business processes and maximize your efficiency.",
    
    // Agent Store
    "store.title": "AI Agent",
    "store.title.highlight": "Store",
    "store.description": "Discover the most suitable AI agents for your needs from thousands of options. Professional solutions from every category are here.",
    "store.search.placeholder": "Search agents...",
    "store.sort.popular": "Popular",
    "store.sort.price": "Price",
    "store.sort.name": "Name",
    "store.view.grid": "Grid",
    "store.view.list": "List",
    
    // Categories
    "category.all": "All",
    "category.writing": "Writing",
    "category.visual": "Visual",
    "category.audio": "Audio",
    "category.analysis": "Analysis",
    "category.chat": "Chat",
    "category.code": "Code",
    "category.language": "Language",
    "category.marketing": "Marketing",
    
    // Agent Status
    "status.active": "Active",
    "status.popular": "Popular",
    "status.new": "New",
    "status.trend": "Trending",
    "status.pro": "Pro",
    "status.automatic": "Automatic",
    
    // Pricing
    "pricing.monthly": "/month",
    "pricing.yearly": "/year",
    "pricing.free": "Free",
    "pricing.free.description": "Start with basic features",
    "pricing.free.feature1": "Limited agent features",
    "pricing.free.feature2": "Low quota usage",
    "pricing.free.feature3": "Basic integrations",
    "pricing.free.limitation1": "No custom integrations",
    "pricing.free.limitation2": "No priority support",
    "pricing.free.button": "Start Free",
    "pricing.free.note": "Cancel anytime",
    "pricing.plus": "Plus",
    "pricing.plus.description": "Advanced features and high quotas",
    "pricing.plus.feature1": "Advanced agent features",
    "pricing.plus.feature2": "High quota usage",
    "pricing.plus.feature3": "High API access",
    "pricing.plus.feature4": "Priority support",
    "pricing.plus.feature5": "Custom integrations",
    "pricing.plus.limitation1": "No unlimited usage",
    "pricing.plus.button": "Try 14 Days Free",
    "pricing.premium": "Premium",
    "pricing.premium.description": "All advanced features and unlimited quotas",
    "pricing.premium.feature1": "More advanced agent features",
    "pricing.premium.feature2": "Unlimited usage",
    "pricing.premium.feature3": "Full API access",
    "pricing.premium.feature4": "24/7 priority support",
    "pricing.premium.feature5": "Custom integrations",
    "pricing.premium.feature6": "Advanced analytics",
    "pricing.premium.feature7": "Team collaboration",
    "pricing.premium.button": "Contact Sales Team",
    "pricing.premium.note": "Contact us for custom pricing",
    "pricing.mostPopular": "Most Popular",
    "pricing.cancelNote": "Cancel anytime",
    "pricing.title": "Choose the Plan",
    "pricing.titleHighlight": "That Suits You",
    "pricing.subtitle": "Suitable plan options for every AI agent. 20% discount opportunity with annual payment.",
    "pricing.paymentOptions.title": "Payment Options",
    "pricing.paymentOptions.description": "Each plan can be purchased annually or monthly. 20% discount per month is applied for annual payments.",
    "pricing.faq.title": "Frequently Asked Questions",
    "pricing.faq.subtitle": "Most frequently asked questions about our pricing plans.",
    "pricing.faq.q1.title": "Are prices calculated per agent?",
    "pricing.faq.q1.answer": "Yes, in Agent Magnet, each agent is sold separately. Each agent's price may be different. You can examine it in detail on the payment page.",
    "pricing.faq.q2.title": "How does annual payment discount work?",
    "pricing.faq.q2.answer": "In annual payment, you pay the 20% discounted monthly fee in advance. This saves you 20% annually.",
    "pricing.faq.q3.title": "Can I choose different plans for different agents?",
    "pricing.faq.q3.answer": "Yes, you can choose different plans for each AI agent. For example, you can use Premium for one agent and Plus for another.",
    "pricing.faq.q4.title": "What should I do for enterprise solutions?",
    "pricing.faq.q4.answer": "You can contact our sales team for multi-agent management, custom integrations, and enterprise solutions.",
    "pricing.contact.title": "Do You Have Special Needs?",
    "pricing.contact.description": "Contact our sales team for enterprise solutions, multi-agent management, custom integrations, and volume discounts.",
    "pricing.contact.button": "Contact Our Team",
    
    // Developer Page
    "developer.title": "Developer",
    "developer.titleHighlight": "Portal",
    "developer.subtitle": "Upload your own AI agent to the platform store and reach users worldwide.",
    "developer.comingSoon.title": "Coming Soon!",
    "developer.comingSoon.description": "Our developer portal is currently under development. It will be available soon. If you're interested in becoming a developer, please leave your email address in the form below. Let's create amazing things together!",
    "developer.comingSoon.button": "Developer Form",
    "developer.benefits.title": "Developer Benefits",
    "developer.benefits.subtitle": "Benefits you'll get by publishing agents on our platform",
    "developer.benefits.global.title": "Global Reach",
    "developer.benefits.global.description": "Reach millions of users worldwide and promote your agent.",
    "developer.benefits.revenue.title": "Earn Revenue",
    "developer.benefits.revenue.description": "Earn up to 70% commission from your agent's sales.",
    "developer.benefits.community.title": "Developer Community",
    "developer.benefits.community.description": "Connect with other developers and share your experiences.",
    "developer.benefits.support.title": "Technical Support",
    "developer.benefits.support.description": "Get supported with 24/7 technical support and development tools.",
    "developer.features.title": "Platform Features",
    "developer.features.subtitle": "Tools and features specially designed for developers",
    "developer.features.sdk.title": "Advanced SDK",
    "developer.features.sdk.description": "Easily integrate your agent with comprehensive API and SDK.",
    "developer.features.easyUpload.title": "Easy Upload",
    "developer.features.easyUpload.description": "Upload your agent with one click and publish it in the store.",
    "developer.features.analytics.title": "Detailed Analytics",
    "developer.features.analytics.description": "Track your agent's performance and usage statistics.",
    "developer.features.marketing.title": "Marketing Support",
    "developer.features.marketing.description": "Marketing tools and campaigns to promote your agent.",
    "developer.stats.title": "Platform Statistics",
    "developer.stats.subtitle": "Growth of our developer community",
    "developer.stats.developers.count": "500+",
    "developer.stats.developers.label": "Developers",
    "developer.stats.agents.count": "1000+",
    "developer.stats.agents.label": "Published Agents",
    "developer.stats.revenue.count": "$2M+",
    "developer.stats.revenue.label": "Total Revenue",
    "developer.stats.countries.count": "50+",
    "developer.stats.countries.label": "Countries",
    
    // My Agents Page
    "myAgents.title": "My Agents",
    "myAgents.description": "Manage and use your purchased agents",
    "myAgents.gmailAgent": "Gmail Agent",
    "myAgents.useGmail": "Use Gmail",
    "myAgents.useAgent": "Use Agent",
    "myAgents.gmailDescription": "Manage your emails with Gmail integration",
    "myAgents.usageCount": "Usage Count:",
    "myAgents.lastUsed": "Last Used:",
    "myAgents.purchaseDate": "Purchase Date:",
    "myAgents.unknown": "Unknown",
    "myAgents.buyMoreAgents": "Buy More Agents",
    "myAgents.noAgentsTitle": "You haven't purchased any agents yet",
    "myAgents.noAgentsDescription": "Start by purchasing an agent from the agent store.",
    "myAgents.goToStore": "Go to Agent Store",
    "myAgents.loading": "Loading your agents...",
    "myAgents.errorTitle": "Error Occurred",
    "myAgents.errorDescription": "An error occurred while loading your agents.",
    "myAgents.tryAgain": "Try Again",
    
    // Agent Detail Page
    "agentDetail.purchase": "Buy Agent",
    "agentDetail.purchasing": "Purchasing...",
    "agentDetail.loginAndPurchase": "Login and Buy Agent",
    "agentDetail.alreadyOwned": "You already own this agent",
    "agentDetail.alreadyOwnedDescription": "Continue using it from My Agents section.",
    "agentDetail.goToMyAgents": "Go to My Agents",
    "agentDetail.planSelection": "Plan Selection",
    "agentDetail.billing": "Billing:",
    "agentDetail.monthly": "Monthly",
    "agentDetail.yearly": "Yearly %20 Discount",
    "agentDetail.planFeatures": "Plan Features",
    "agentDetail.planIntegrations": "Available Integrations in the Plan",
    "agentDetail.monthlySubscription": "Monthly Subscription",
    "agentDetail.yearlySubscription": "Yearly Subscription",
    "agentDetail.perYear": "/year",
    "agentDetail.cancelAnytime": "You can cancel at any time. No credit card required.",
    "agentDetail.fastSetup": "Fast Setup",
    "agentDetail.secure": "Secure",
    "agentDetail.globalAccess": "Global Access",
    "agentDetail.demoNote": "This plan is not yet available in our demo version. It is being worked on.",
    "agentDetail.backToAgents": "Back to Agents Store",
    "agentDetail.free": "Free",
    "agentDetail.perMonth": "/month",
    "agentDetail.freeDescription": "Unlimited free",
    "agentDetail.yearlyPayment": "yearly payment",
    "agentDetail.yearlySavings": "Save 20% with yearly payment!",
    "agentDetail.freeCreditCard": "No credit card required. You can upgrade anytime.",
    "agentDetail.moreInPremium": "more in premium",
    "agentDetail.planSelectionTitle": "Plan Selection",
    "agentDetail.monthlyToggle": "Monthly",
    "agentDetail.yearlyToggle": "Yearly %20 Discount",
    "agentDetail.freePlan": "Free",
    "agentDetail.plusPlan": "Plus",
    "agentDetail.premiumPlan": "Premium",
    "agentDetail.popular": "Popular",
    "agentDetail.dailyQueries": "5 daily queries",
    "agentDetail.last10Emails": "Summaries of your last 10 emails",
    "agentDetail.emailExtension": "Works with email addresses ending in example@gmail.com",
    "agentDetail.demoPlanNote": "This plan is not yet available in our demo version. It is being worked on.",
    
    // Agent Start Page
    "agentStart.title": "Login",
    "agentStart.description": "agent to use it, you need to login first.",
    "agentStart.whyLogin": "Why should I login?",
    "agentStart.loginReason1": "We can track your agent usage",
    "agentStart.loginReason2": "Secure and personalized experience",
    "agentStart.loginReason3": "You can see your usage history",
    "agentStart.googleLogin": "Login with Google",
    
    // Gmail Agent Usage
    "gmail.title": "Gmail Agent",
    "gmail.loginRequired": "You need to login to use this feature.",
    "gmail.connectAccount": "Connect My Gmail Account",
    "gmail.getEmails": "Get Last 10 Emails and Summarize",
    "gmail.loading": "Loading Emails and AI Summarizing...",
    "gmail.aiFeature": "AI Summarization Feature",
    "gmail.aiFeature1": "AI summary is created for each email",
    "gmail.aiFeature2": "Processed gradually due to rate limits (2 second intervals)",
    "gmail.aiFeature3": "Turkish, short and concise summaries",
    "gmail.aiFeature4": "Google Gemini 2.0 Flash model is used",
    "gmail.description": "View your recent emails from Gmail account and summarize with AI",
    "gmail.backToAgent": "Back to Agent",
    "gmail.connectGmail": "Connect My Gmail Account",
    "gmail.loadingEmails": "Loading emails...",
    "gmail.showSnippets": "Show Snippets",
    "gmail.hideSnippets": "Hide Snippets",
    "gmail.recentEmails": "Recent Emails",
    "gmail.aiSummary": "AI Summary",
    "gmail.noEmails": "No Emails Found",
    "gmail.noEmailsDescription": "No emails found in your Gmail account or you haven't fetched emails yet.",
    "gmail.connectRequired": "Gmail Connection Required",
    "gmail.connectDescription": "Connect your Gmail account to view and summarize your emails with AI.",
    "gmail.accountConnected": "Your Gmail account is connected - You can fetch your emails",
    "gmail.disconnect": "Disconnect",
    "gmail.connectionExpired": "Gmail Connection Expired",
    "gmail.connectionExpiredDesc": "Your connection with Gmail account has expired. You need to reconnect to view your emails.",
    "gmail.connectionExpiredReason": "This usually happens for security reasons or when not used for a long time.",
    "gmail.connectionActive": "Gmail Connection Active",
    "gmail.connectionActiveDesc": "You can view and summarize your emails.",
    "gmail.reconnect": "Reconnect",
    "gmail.getLast10Emails": "Get Last 10 Emails",
    "gmail.dailyUsageText": "You have used {used}/{total} of your daily usage rights",
    "gmail.reset": "Reset",
    "gmail.remaining": "remaining",
    "gmail.lastRightsRemaining": "Last {count} rights remaining",
    "gmail.dailyLimitReached": "Daily limit reached. Try again tomorrow.",
    
    // Common
    "common.loading": "Loading...",
    "common.error": "Error Occurred",
    "common.try_again": "Try Again",
    "common.tomorrow": "Tomorrow",
    "common.today": "Today",
    "common.days": "d",
    "test.loadingAgents": "Loading agents...",
    "test.loadingAuth": "Loading auth...",
    "test.testIntegration": "Test the integration",
    "test.testIntegrationDesc": "by clicking \"Test API Connection\"",
    "common.back_home": "Back to Home",
    
    // Footer
    "footer.platform": "Platform",
    "footer.support": "Support",
    "footer.help": "Help Center",
    "footer.docs": "Documentation",
    "footer.contact": "Contact",
    "footer.community": "Community",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.cookies": "Cookies",
    "footer.rights": "© 2025 Agent Magnet. All rights reserved.",
    
    // 404 Page
    "notFound.title": "404 Page Not Found",
    "notFound.description": "Did you forget to add the page to the router?"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("language");
      return (saved as Language) || "tr";
    }
    return "tr";
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("language", lang);
    document.documentElement.lang = lang;
  };

  const getCategoryMapping = (category: string) => {
    const mapping = {
      "Yazım": { tr: "Yazım", en: "Writing" },
      "Görsel": { tr: "Görsel", en: "Visual" },
      "Ses": { tr: "Ses", en: "Audio" },
      "Analiz": { tr: "Analiz", en: "Analysis" },
      "Sohbet": { tr: "Sohbet", en: "Chat" },
      "Kod": { tr: "Kod", en: "Code" },
      "Dil": { tr: "Dil", en: "Language" },
      "Pazarlama": { tr: "Pazarlama", en: "Marketing" }
    };
    
    // Find the category by checking both tr and en values
    const entry = Object.entries(mapping).find(([key, value]) => 
      value.tr === category || value.en === category || key === category
    );
    
    return entry ? entry[1][language] : category;
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, getCategoryMapping }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}